apiVersion: v1
kind: Secret
metadata:
  name: template-supa-secrets
type: Opaque
stringData:
  DATABASE_URL: postgresql://postgres:postgres@db.internal:5432/postgres
  SUPABASE_URL: https://YOUR-PROJECT.supabase.co
  SUPABASE_ANON_KEY: your-public-anon-key
  SUPABASE_SERVICE_ROLE_KEY: your-service-role-key
